### ISSUE TITLE
qri delete --all must cap-off a logbook

### ISSUE THREAD

**Issue by b5** [qri-io/qri#996] opened 2019-11-04 16:39 UTC
Currently, deleting an entire dataset isn't closing off history with a name-deletion operation. running `qri delete --all` should _close out that dataset name_, returning the name to the available namespace. running `qri init` with the same name must create a completely separate history.

Let's write a test that proves this isn't happening & then refactor-to-passing.

**Comment by dustmop** [comment] 2019-11-04 16:45
Duplicate of https://github.com/qri-io/qri/issues/993.

**Closed by dustmop** 2019-11-04 16:45 UTC
Labels: bug, logbook
