### ISSUE TITLE
`qri get` will only return an empty object

### ISSUE THREAD

**Issue by osterbit** [qri-io/qri#508] opened 2018-07-27 17:37 UTC
- get the same result whether I provide a path (like `qri get meta`) or without one
- link to the [dataset.yaml and body data.json](https://gist.github.com/osterbit/26728878c8a77ce2628352abfab9ec91) in a gist
- I tried including the full path as mentioned in #479 but get same result

**Comment by dustmop** [comment] 2018-07-30 16:14
I tried to create my own version of the dataset using: `qri add --file=dataset.yaml --body=data.json me/test_repo`, and `qri get meta` works fine. This implies there's something specific to the particular instance of the dataset.

**Comment by dustmop** [comment] 2018-07-30 16:18
When I try to get the contents of the same dataset that @osterbit was speaking about, I get an entirely different error:

```
> qri get meta color_dog2/paris_energy_pledges3
error loading dataset: error getting file bytes: error resolving hash: selected encoding not supported
```

Going to investigate.

**Comment by dustmop** [comment] 2018-07-31 17:50
More info:

When I ran `qri add color_dog2/paris_energy_pledges3` to add the dataset to my repo, then `qri get color_dog2/paris_energy_pledges3` would work properly for me.

On @osterbit's end, running `qri use color_dog2/paris_energy_pledges3` followed by `qri get` would properly get the data. I think this is a duplicate of https://github.com/qri-io/qri/issues/492?

**Comment by dustmop** [comment] 2018-08-20 18:36
Talking with @osterbit, this appears to be fixed now, indeed with the same root cause as #492.

**Closed by dustmop** 2018-08-20 18:36 UTC
Labels: bug, ready
