### ISSUE TITLE
nil pointer error when attempting to save empty csv file

### ISSUE THREAD

**Issue by chriswhong** [qri-io/qri#1312] opened 2020-04-27 15:45 UTC
When running an external data pipeline, I ended up with an empty CSV file.  I attempted to run the following qri command and got a the invalid memory address or nil pointer dereference message.

```
$ qri save nyc-transit-data/turnstile_daily_counts_2020 --body tmp/daily_counts_2020.csv --title "update data for week ending April 25, 2020"
⠐ panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x468cce9]
goroutine 10 [running]:
github.com/qri-io/deepdiff.bestCandidate(0xc00e352000, 0x1984, 0x1e00, 0x5b0a900, 0xc0003948c0, 0x1)
	/Users/chriswhong/go/pkg/mod/github.com/qri-io/deepdiff@v0.1.1-0.20200305020550-8173efebcaa1/deepdiff.go:191 +0x69
github.com/qri-io/deepdiff.(*diff).queueMatch.func1(0xc00b9b62a0, 0xc00017fc50, 0xc00e3d4100, 0x1, 0xc00b9b6300)
	/Users/chriswhong/go/pkg/mod/github.com/qri-io/deepdiff@v0.1.1-0.20200305020550-8173efebcaa1/deepdiff.go:154 +0x182
created by github.com/qri-io/deepdiff.(*diff).queueMatch
	/Users/chriswhong/go/pkg/mod/github.com/qri-io/deepdiff@v0.1.1-0.20200305020550-8173efebcaa1/deepdiff.go:131 +0xec
```

**Comment by dustmop** [comment] 2020-04-28 22:05
Hmmm. Just `touch`ing a file, then `save`ing with it doesn't lead to a segfault. So something else is going on here....

**Comment by xxristoskk** [comment] 2020-05-13 23:41
Running into the same issue here.
`⠙ panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xa4a118]

goroutine 84 [running]:
github.com/qri-io/deepdiff.bestCandidate(0xc017b58000, 0x18f, 0x200, 0x1dcda00, 0xc000338c80, 0xa0546e)
	/Users/b5/go/pkg/mod/github.com/qri-io/deepdiff@v0.1.1-0.20200305020550-8173efebcaa1/deepdiff.go:196 +0x248
github.com/qri-io/deepdiff.(*diff).queueMatch.func1(0xc00e5f99e0, 0xc002d1e3c0, 0xc00e82c0e8, 0xa0546e, 0xc00e5f9a40)
	/Users/b5/go/pkg/mod/github.com/qri-io/deepdiff@v0.1.1-0.20200305020550-8173efebcaa1/deepdiff.go:154 +0x182
created by github.com/qri-io/deepdiff.(*diff).queueMatch
	/Users/b5/go/pkg/mod/github.com/qri-io/deepdiff@v0.1.1-0.20200305020550-8173efebcaa1/deepdiff.go:131 +0xec`

**Comment by dustmop** [comment] 2020-05-13 23:58
@xxristoskk what was the command you ran to get this segfault? Was this a new dataset or an existing one? Can you recall the exact steps used to recreate this crash from a fresh state? Could you share the body file you were using?

**Comment by xxristoskk** [comment] 2020-05-14 17:23
@dustmop Its a new dataset that I recently published. I made some changes to a dataset's header names, dropped a column, and also modified the readme and meta files. Then I ran the command:

$ qri save --body ~/projects/COVID-prisons/ucla_covid_prison_project_history.csv

Here's a link to the body.
https://drive.google.com/open?id=14kUrES8c_TQkU4ZDFxqZbeJWXMC-fxhV

**Comment by dustmop** [comment] 2020-05-19 01:42
So this bug is pretty tricky to track down. I'm certain that it's happening in `generateCommitDescriptions` in `base/dsfs/dataset.go`. This code path is run by save and uses `deepdiff` to compare the dataset being created with the most recent version that was saved. However, the cause of the crash is entirely dependent on what's in the dataset, both the previous version and new version, specifically the body and structure, so unfortunately the stacktrace alone isn't very helpful. I'm also not very familiar with the inner working of `deepdiff`, that's much more @b5's area, so I can't guess very well what would cause it to crash.

What would be especially helpful would be a sequence of commands, and the relevant body and structure files for each command, in order to have a step-by-step guide that could reproduce the crash when starting at zero. Without that I don't know how to diagnose what's causing the crash to happen.

**Comment by xxristoskk** [comment] 2020-05-27 14:56
@dustmop So I tried this again when updating the body with the most recent data, and I didn't get any errors! A couple headers were removed, a few header names where changed (white space replaced with "."), and many more rows added.

**Comment by xxristoskk** [comment] 2020-08-03 22:47
@dustmop @b5 I ran into this error again today when trying to correct a mistake I made when cleaning the dataset **xristosk/ra_event_details**.

1st commit:
  * Changes to body: 
    * Used `strip()` function when trying to remove **.csv** from the names in the `club_name` column.
      * Turned the `lineup` column into strings rather than arrays to make it more compatible with Qri Cloud
  * Changes to structure:
    * Modified structure.json to reflect the changes to the `lineup` column. 

2nd commit:
  * Changes to body:
    * Realizing that the `strip()` function removed all the characters in ".csv" I went back and used a more appropriate function that removed only **.csv** from the names.

It was during the 2nd commit this error came up.

```⠋ panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xab11b8]

goroutine 30 [running]:
github.com/qri-io/deepdiff.bestCandidate(0xc007516f00, 0x9, 0x10, 0x2162d00, 0xc00636efa0, 0x36be79)
	/Users/ramfox/go/pkg/mod/github.com/qri-io/deepdiff@v0.2.0/deepdiff.go:196 +0x248
github.com/qri-io/deepdiff.(*diff).queueMatch.func1(0xc004bcd4a0, 0xc000278ea0, 0xc004be81b8, 0x36be79, 0xc004bcd500)
	/Users/ramfox/go/pkg/mod/github.com/qri-io/deepdiff@v0.2.0/deepdiff.go:154 +0x182
created by github.com/qri-io/deepdiff.(*diff).queueMatch
	/Users/ramfox/go/pkg/mod/github.com/qri-io/deepdiff@v0.2.0/deepdiff.go:131 +0xec
```

**Comment by xxristoskk** [comment] 2020-08-04 15:40
@dustmop 

Here is the diff-debug.txt
https://drive.google.com/file/d/1NvwnjJCHWTDkfEwtZ1haFgEWbjMG40YT/view?usp=sharing

**Comment by dustmop** [comment] 2020-08-04 16:32
Success! This allows me to reproduce the segfault on my machine, now I can dive in and figure out what's going wrong to cause the crash. Thanks for the help!

**Comment by dustmop** [comment] 2020-08-10 18:13
This is now fixed by https://github.com/qri-io/deepdiff/pull/11 and https://github.com/qri-io/qri/commit/2f5e42cc6bbe751c3961fa6117f95a060de10574, and the newest release of qri includes the fix.

**Closed by dustmop** 2020-08-10 18:13 UTC
Labels: bug
