### ISSUE TITLE
potential bug while saving dataset update

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#293] opened 2018-03-02 19:43 UTC
Removing content from a field doesn't work, because the Assign() function will always ignore empty fields.

This might be what we want -> you can't ever leave a dataset less detailed then you found it, but also we have no feedback/documentation that updating/saving works this way.

Should it work this way? Should there be a way to clear fields?

@b5 @osterbit

**Comment by b5** [comment] 2018-03-02 19:55
yeah I've been thinking about this for a while (apologies, I've known this bug exists, should have raised the issue sooner).  `null` (`nil` in golang) as an explicit clearing method, but that'll require a bunch of custom marshaling for non-pointer struct fields (strings, ints, etc).

The other option is to change the semantics of our update method to distinguish between updating part or all of a model. For example, HTTP PATCH requests are an underused feature intended to deal with this "I only want to change a few fields" issues, whereas HTTP PUT traditionally requires full representations of the model to update (all fields specified).

This intersects with the "set a field to empty" problem b/c if we know the user has given us a _complete_ representation of the model, we can skip the use of `Assign` altogether, so peers can set fields to empty by submitting full representations.

How does this work on the CLI? I have no effing idea. Params that take file? maybe. on the API we can leverage PATCH & PUT semantics. Either way we should start to think about getting these concepts into `qri/core`

**Comment by ramfox** [comment] 2018-03-02 19:58
okay cool thanks for the response
def food for thought

**Comment by b5** [comment] 2018-12-05 13:09
This is a duplicate of #403, and I like that title better, so let's finish discussion over there 😄

**Closed by b5** 2018-12-05 13:09 UTC
Labels: bug, duplicate, question
